### ISSUE TITLE
Export markdown files

### ISSUE THREAD

**Issue by voracious** [voracious/octo#142]
As a user, I would like to download my archive as raw Markdown files with metadata stored as [Front Matter](https://jekyllrb.com/docs/front-matter/) or [an alternative](https://stackoverflow.com/questions/44215896/markdown-metadata-format).

### Resources

- [FileSaver.js](https://github.com/eligrey/FileSaver.js)
- [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js)
- [jszip](https://github.com/Stuk/jszip)

**Comment by voraciousdev** [comment]
[This article](https://ourcodeworld.com/articles/read/189/how-to-create-a-file-and-generate-a-download-with-javascript-in-the-browser-without-a-server) might be useful too.

**Comment by lyqht** [comment]
I can try out this too since I worked on the other issue!
