### ISSUE TITLE
GitHub OAuth does not redirect to app

### ISSUE THREAD

**Issue by editorrust** [voracious/octo#219]
When signing in with GitHub OAuth for the first time, it just reloads the page. This could be confusing. Well, I got confused anyhow 😁

**Comment by voracious** [comment]
@Squirrel-314 were you using Firefox by chance? If so, it might be related to #210.

**Comment by Squirrel-314** [comment]
I tried with mobile versions of Safari & Chrome

**Comment by Squirrel-314** [comment]
I think the problem is not redirect but the fact that you cannot sign in through GitHub on mobile devices. But I am running iPadOS 16.2 beta so that would effect Safari, but I can’t sign in on Chrome either.

**Comment by voracious** [comment]
@Squirrel-314 all browsers on iOS actually run through Safari's browser engine. I'll have to see if I can reproduce this with an emulator.

**Comment by voracious** [comment]
This has been solved along with #239.
