### ISSUE TITLE
Add tabs for recent docs

### ISSUE THREAD

**Issue by voracious** [voracious/octo#227]
### Discussed in https://github.com/voracious/octo/discussions/205

<div type='discussions-op-text'>

<sup>Originally posted by **wbconnor** August 12, 2022</sup>
Was working in Octo today and was switching between two documents a lot. Tabs would have been a huge help.</div>

**Comment by rlnorthcutt** [comment]
This is great! Thanks

**Comment by voracious** [comment]
@rlnorthcutt glad to hear it! 🎉
